version: "3"
services:
    console:
        build: .
        env_file: .env
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - 1433:1433
        environment:
            SA_PASSWORD: "P@ssword1" #defaults: username: 'SA' | server: 'localhost'
            ACCEPT_EULA: "Y"