version: "3"
services:
    console:
        build: .
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "P@ssword1"
            ACCEPT_EULA: "Y"